version: "3.9"

services:

  backend:
    build: ./backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0

  frontend:
    build: ./frontend
    container_name: vue_app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run serve

  db:
    image: postgres:15
    container_name: pgsql_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgintradmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: aminelebrini4@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5060:80"
    depends_on:
      - db

volumes:
  pgdata:
